[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[build-dependencies]
nasm-rs = "0.2.1"

[dependencies]
volatile = "0.2.6"

[dependencies.spin]
version = "= 0.9.2"

[dependencies.lazy_static]
git = "https://github.com/rust-lang-nursery/lazy-static.rs"
features = ["spin_no_std"]
